### ISSUE TITLE
Update CMIPLib.py for py3

### ISSUE THREAD

**Issue by durack1** [durack1/CMIPLib#1]
Many of the existing print statements need to be py3-erized, a simple
```
from __future__ import print_function
```
And parentheses around the print statements should solve the issue.

In addition:
```
import ..cPickle..
```
Will need to be updated to:
`import pickle as cPickle` as noted [here](http://forums.fast.ai/t/no-module-named-cpickle/3171) and [here](https://askubuntu.com/questions/742782/how-to-install-cpickle-on-python-3-4)

@pochedls

**Comment by pochedls** [comment]
This was essentially done, though Python 3 cdscan was frequently hanging. This needs to be documented and opened as a ticket in that repository.

**Comment by pochedls** [comment]
This was done before, but there were issues with cdat when logging was on. Turning this off enables us to use py3.

**Comment by durack1** [comment]
Ok great, so are you now operating in a py3 env?

**Comment by pochedls** [comment]
So far - I haven't tried to create a bunch of xmls yet, though.

**Comment by durack1** [comment]
Ok great, looking forward to pushing to a pure py3 env in the near future then
