### ISSUE TITLE
CMIP database consider file/dir status changes

### ISSUE THREAD

**Issue by durack1** [durack1/CMIPLib#2]
It would be useful to track behavior/status changes through time, so that if a dataset is corrected, or the behavior of cdscan changes through time, we have a record of this.
```
$path/$.nc(s) - WARNING 1 time axis issue
""            - WARNING 2 latitude problem ; # Potentially due to a cdscan change
```

The advantage of capturing this information is that we can monitor changes with both the files/dirs, and also changes due to software patches/problems/issues

**Comment by pochedls** [comment]
@durack1 - In the SQL database, we currently record errors during cdscan. We could create another table that simply logs this information over time. This could be setup as a report that e-mails out (and is recorded in the db) on a weekly-ish basis. 

| Date | Table | Category | Count | 
| - | - | - | - |
| 2018-01-01 | cmip5 | memory error | 22 | 
| 2018-01-01 | cmip5 | duplicate directory | 36232 | 
| 2018-01-01 | cmip5 | total path count | 856101 | 
| 2018-01-01 | cmip5 | total xml count | 182012 | 

An alternative (and complementary) approach would be to simply dump the database to file on a weekly basis.

**Comment by durack1** [comment]
@pochedls I am sure that @gleckler1 will have an opinion on this, for that matter so might @taylor13

In particular, I'm not sure that @gleckler1 is going to want to play "database" when he doesn't seem to want to play "gz archive" - Pete G over to you..

**Comment by durack1** [comment]
I am currently going through logs dating back to February 2012 that provide the only history of the CMIP5 database building that I have direct access. It would be useful as CMIP6 data starts to be replicated, if we can keep a track of changes, say at weekly intervals, so we can review progress over time.

I suggest we keep track of the CMIP6 data paths, and files over time.

This will be a useful data source to have when reviewing hardware etc requirements in the future

@pochedls a discussion on this would be useful

ping @sashakames @painter1 @cmharr @taylor13

**Comment by pochedls** [comment]
@durack1 - are there specific metrics you want dumped out to the database? We can add things later, but I'd like to get this working and close out this ticket. I may just dump out the number of xmls and the total number of directories for now.

**Comment by durack1** [comment]
The total number of directories would be perfect, as would xmls. That's all I can think of. Doing this per project (CMIP5, CMIP6) would also be good

**Comment by pochedls** [comment]
I have an initial commit 561e4d0dad0fa9cf695d8eeb8d82c6461cfcd1f1 of this in. We can add on more stats as they make sense...
