### ISSUE TITLE
Mechanism to update existing xmls

### ISSUE THREAD

**Issue by pochedls** [durack1/CMIPLib#6]
Several paths may contain the exact same data and would write out the same xml file. To make sure I had the correct directory-xml pair, I checked to see if an xml was already written before processing a directory. If an xml was already written, the code records that an xml was already written for that data [(here)](https://github.com/durack1/CMIPLib/blob/master/lib/CMIPLib.py#L334). 

This is problematic if a directory is updated. The current logic would state that an xml already exists for this path and not re-run cdscan. This logic needs to be updated such that if the xml is related to a directory that has been modified, the xml and xml date should be updated.

**Comment by durack1** [comment]
@pochedls this is a perfect candidate for the `creation_date` scan, as this information should more accurately record which of these file groups was written most recently

**Comment by pochedls** [comment]
To do this, we should: 
1. delete existing xmls
2. update the database (to reflect the xml is gone)
3. re-run the code

**Comment by durack1** [comment]
I would prefer that we run this under the cmip5-dyn subdir, validate the outputs against cmip5 and cmip5-test, and once we're happy that we're in good shape, rename the old dirs something and replace cmip5-dyn -> cmip5

**Comment by pochedls** [comment]
> I would prefer that we run this under the cmip5-dyn subdir, validate the outputs against cmip5 and cmip5-test, and once we're happy that we're in good shape, rename the old dirs something and replace cmip5-dyn -> cmip5

This will all be run in the cmip-dyn directory. This ticket is related to the situation where a xml file is already in place (in cmip-dyn) and we choose to re-create it (maybe it had an error and cdat has an update that may correct the error).

**Comment by pochedls** [comment]
Need to specify replaceXml=True in process_path in order to replace existing paths. 

This can be used when regenerating xml files with errors.
