### ISSUE TITLE
Ensure building of CMIP6 database can be tracked

### ISSUE THREAD

**Issue by durack1** [durack1/CMIPLib#7]
I am currently going through logs dating back to February 2012 that provide the only history of the CMIP5 database building that I have direct access. It would be useful as CMIP6 data starts to be replicated, if we can keep a track of changes, say at weekly intervals, so we can review progress over time.

I suggest we keep track of the CMIP6 data paths, and files over time.

This will be a useful data source to have when reviewing hardware etc requirements in the future

@pochedls a discussion on this would be useful

ping @sashakames @painter1 @cmharr @taylor13

**Comment by pochedls** [comment]
Is this the same as #2?

**Comment by durack1** [comment]
@pochedls it could be, I'll migrate my comment above across and close this as a dupe

**Comment by durack1** [comment]
Closed as dupe of https://github.com/durack1/CMIPLib/issues/2#issuecomment-407832381
