### ISSUE TITLE
Write out invalid directories

### ISSUE THREAD

**Issue by pochedls** [durack1/CMIPLib#8]
The current algorithm parses all of the directories and if the directory **clearly**<sup>*</sup> doesn't have the correct directory structure it basically gets ignored. We should probably log these or write them to a separate table. 

<sup>*</sup> clearly in that: the algorithm doesn't have hardcoded variables/rips/models/etc. so directories could have incorrect names or out of order subdirectories and this would not be detected. This doesn't appear to be a major problem at the moment.

**Comment by pochedls** [comment]
These paths are written out to an invalid_paths table.

**Comment by durack1** [comment]
@pochedls I had if statements for paths in cmip5, I assume the #1 and #8 address these quirks?

**Comment by pochedls** [comment]
@durack1 - I'm not sure what you mean. The dynamic library has `if` statements, too. This ticket just logs the directories that can't be parsed into a SQL table.

**Comment by durack1** [comment]
Sorry with this I meant that the CMIP5 paths that have been parsed previously had two distinct cases, with the directory ordering different for each (but consistent within each case, or subpath, e.g. css01/scratch vs css02/data). I assume you have pulled that logic across?

**Comment by pochedls** [comment]
Hi @durack1  - Yes the function `parsePath` in CMIPLib recognizes the two CMIP5 path types and acts accordingly.

**Comment by durack1** [comment]
@pochedls nice, [`parsePath`](https://github.com/durack1/CMIPLib/blob/master/lib/CMIPLib.py#L179-L262). I note that in you've used `re` in some of the other functions (like [`produceCMIP5Activity`](https://github.com/durack1/CMIPLib/blob/master/lib/CMIPLib.py#L156)) which I think is a good way to go, particularly as we can use the CMIP6_CVs dictionaries to link activityId with experiment
